### ISSUE TITLE
is_list() ?

### ISSUE THREAD

**Issue by dineshbvadhia** [insightindustry/validator-collection#82]
Is there a reason why there isn't a `is_list()` checker and validator?

**Comment by insightindustry** [comment]
@dineshbvadhia Primarily because the ``checkers.is_iterable()`` or ``validators.iterable()`` functions satisfy the practical requirement. If you're looking to check whether a variable is a ``list`` instance specifically, you can accomplish that using the Python standard library's ``isinstance(<variable>, list)`` function. But a more typical use case (at least in my thinking) is to evaluate whether something is an iterable - which may be a ``list``, it may be a set, it may be a ``tuple``, etc. 

Is there a use case you see for validating/checking whether something is a ``list`` specifically, rather than validating/checking that it is an iterable?

**Comment by dineshbvadhia** [comment]
Got it. Thank-you.

Follow on question. With a list of strings, for example, you'd check the object was a list first. If it is then check each element is a string. Finally, validate each element as a string. Is that about right?

**Comment by insightindustry** [comment]
Pretty much, though stylistically I'd probably choose do it in a two-step process using a list comprehension:

```
as_iterable = validators.iterable(value, forbid_literals = [str, bytes, dict])

as_iterable = [validators.string(x) for x in as_iterable]
```

**Comment by insightindustry** [comment]
Closing the issue since it seems to be resolved.
